# config/_default/languages.en.toml

title = "Purple Shirt Dev"

[params.author]
name = "Garrett Moseke"
image = "img/author.jpg"
headline = "The purple shirt is where my personality comes from."
bio = "Software engineer, avid runner, and sometimes I write. I'm a child of the desert and mountains living in the flattest, rainiest country on earth."
links = [
    { github = "https://github.com/GNMoseke" },
    { linkedin = "https://www.linkedin.com/in/garrett-moseke/" },
    { email = "mailto:gmosedev@proton.me" },
]
